# Generated by Django 2.0.9 on 2018-12-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(max_length=200, null=True, upload_to='volunteer'),
        ),
    ]
