# Generated by Django 2.0.9 on 2018-12-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(max_length=200, null=True, upload_to='static/uploads'),
        ),
    ]
